version: '3.1'
networks:
  quest_postgresql:
    external: false

services:
  db-server:
    container_name: quest_postgresql
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: quest
      POSTGRES_PASSWORD: secret
    networks:
      - quest_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local